---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Creating EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: mayur_keyvalue
        security_group: default
        instance_type: t2.micro
        region: us-east-1
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        network:
          assign_public_ip: true
        image_id: "{{ item.image }}"
        tags:
          environment: "{{ item.name }}"
      loop:
        - { image: "ami-0c02fb55956c7d316", name: "manage-node-1" }
        - { image: "ami-053b0d53c279acc90", name: "manage-node-2" }
        - { image: "ami-053b0d53c279acc90", name: "manage-node-3" }
